config/routes.rb
Rails.application.routes.draw do

  root 'suggestions#index'

    
    match '/usuarios/set_admin/:id', to: 'usuarios#set_admin', via: 'patch', as: 'set_usuario_admin'
    match '/reset_password', to: 'usuarios#reset_password', via: 'get'
    match '/send_reset_password', to: 'usuarios#send_reset_password', via: 'post'
    match '/confirm_account/:id', to: 'usuarios#confirm_account', via: 'get'
    match '/usuarios/:id/edit_preferences', to: 'usuarios#edit_preferences', via: 'get', as: 'edit_preferences'
    match '/usuarios/:id/update_preferences:id', to: 'usuarios#update_preferences', via: 'patch'
    match '/usuarios/:id/edit_password', to: 'usuarios#edit_password', via: 'get', as: 'edit_password'
    match '/usuarios/:id/update_password', to: 'usuarios#update_password', via: 'patch'
    match '/signup', to: 'usuarios#new', via: 'get'

    match '/signin',  to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    match '/collaborative_recommendation', to: 'itens#collaborative_recommendation', via: 'get'
    match '/refresh_item_img/:id', to: 'itens#refresh_item_img', via: 'get'
    match '/content_recommendation/:id', to: 'itens#content_recommendation', via: 'get'

    match '/avaliacoes', to: 'avaliacoes#create_update', via: 'post'

    match '/generalizacoes/destroy_all', to: 'generalizacoes#destroy_all', via: 'post'

    match 'auth/:provider/callback', to: 'sessions#create_facebook', via: 'get'
    match 'auth/failure', to: redirect('/'), via: 'get'

    match '/sobre', to: 'suggestions#sobre', via: 'get'
    match '/privacidade', to: 'suggestions#privacidade', via: 'get'
    match '/termos', to: 'suggestions#termos', via: 'get'
    match '/contato', to: 'suggestions#contato', via: 'get'
    match '/suggestions/enviar_contato', to: 'suggestions#enviar_contato', via: 'post'

    resources :relacoes, only: [:create, :destroy]

    resources :generos, :categorias, :generalizacoes, :itens, :usuarios, :flags

    resources :avaliacoes, only: :update

    resources :comentarios, only: [:create, :destroy, :edit, :update, :show]

    resources :sessions, only: [:new, :create, :destroy]

    resources :usuarios do
      member do # poderia ser collection
        get :seguindo, :seguidores
      end
    end

  match ':controller(/:action(/:id(.:format)))', via: 'get'
  

end

app/models/genero.rb
class Genero < ActiveRecord::Base
	
	before_validation :strip_spaces

	validates_presence_of :nome, message: "deve ser preenchido!"
	validates_uniqueness_of :nome, message: "já cadastrado!"

	has_many :generalizacoes, dependent: :destroy
	has_many :itens, through: :generalizacoes

	has_many :flags, as: :flagavel, dependent: :destroy

	searchable do
    text :nome, boost: 5
    text :descricao
  end

  def get_name 
  	self.nome
  end

	#-------------------------- 
	#-                        -
	#-    Métodos Publicos    -
	#-                        -
	#--------------------------

  #-------------------------- 
  #-                        -
  #-    Métodos Privados    -
  #-                        -
  #--------------------------

	private
		def strip_spaces
			self.nome = nome.squeeze.strip if attribute_present?("nome")
		end

end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  helper_method :sort_coluna, :sort_direcao
  
  before_action :set_genero, only: [:show, :edit, :update, :destroy]

  # GET /generos
  # GET /generos.json
  def index
    @q = params[:q]

    if @q and !@q.blank?
      @search = Genero.search do
        keywords params[:q]
        paginate(page: params[:page], :per_page => 30)
      end
      @generos = @search.results
    else
      @generos = Genero.order(sort_coluna + " " + sort_direcao).paginate(page: params[:page], :per_page => 30)
    end

    @generos_count = @generos.size

  end

  # GET /generos/1
  # GET /generos/1.json
  def show
    @itens = @genero.itens.group("itens.id").paginate(page: params[:page], :per_page => 30)
  end

  # GET /generos/new
  def new
    @genero = Genero.new
  end

  # GET /generos/1/edit
  def edit
  end

  # POST /generos
  # POST /generos.json
  def create
    @genero = Genero.new(genero_params)

    if params.has_key?(:usa_wiki)
      @genero.descricao = Utils::descricao_wiki(@genero.nome)
      if @genero.descricao.nil?
        flash.now[:danger] = "Não foi possível buscar a descrição do Wikipédia"
        render :new
        return
      end
    end

    respond_to do |format|
      if @genero.save
        flash[:success] = "Gênero #{@genero.nome} foi criado com sucesso!"
        format.html { redirect_to @genero }
        format.json { render :show, status: :created, location: @genero }
      else
        flash.now[:danger] = "Gênero #{@genero.nome} não foi criado com sucesso!"
        format.html { render :new }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generos/1
  # PATCH/PUT /generos/1.json
  def update
    respond_to do |format|
      if @genero.update(genero_params)
        flash[:success] = "Gênero #{@genero.nome} foi editado com sucesso!"
        format.html { redirect_to @genero }
        format.json { render :show, status: :ok, location: @genero }
      else
        flash.now[:danger] = "Gênero #{@genero.nome} não foi editado com sucesso!"
        format.html { render :edit }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generos/1
  # DELETE /generos/1.json
  def destroy
    @genero.destroy
    respond_to do |format|
      flash[:success] = "Gênero #{@genero.nome} foi excluido com sucesso!"
      format.html { redirect_to generos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genero
      @genero = Genero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genero_params
      params.require(:genero).permit(:nome, :descricao)
    end

    def sort_coluna
      Genero.column_names.include?(params[:coluna]) ? params[:coluna] : "id"
    end

    def sort_direcao
      %w[asc desc].include?(params[:direcao]) ? params[:direcao] : "asc"
    end
      
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/views/generos/_edit_form.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
	  <%= form_for(@genero) do |f| %>
	    <%= render 'compartilhado/mensagens_erro', object: f.object %>
	    <div class="form-group">
	    <%= f.label :nome, "Gênero" %>
	    <%= f.text_field :nome, class: "form-control", disabled: !admin? %>
	    </div>
	    <div class="form-group">
	    <%= f.label :descricao, "Descrição" %>
	    <%= f.text_area :descricao, rows: 6, class: "form-control" %>
	    </div>
	    <hr>
	    <%= f.submit "Enviar", class: "btn btn-large btn-primary" %>
	    <hr>
	    NOTA: O mau uso do sistema Suggest Me resultará na expulsão do usuário do site.
	  <% end %>
	</div>
</div>

app/views/generos/_form.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
	  <%= form_for(@genero) do |f| %>
	    <%= render 'compartilhado/mensagens_erro', object: f.object %>
	    <div class="form-group">
	    	<%= f.label :nome, "Gênero" %>
	    	<%= f.text_field(:nome, class: "form-control") %>
	    </div>
	    <div class="form-group">
	    	<%= f.label :descricao, "Descrição" %>
	    	<%= f.text_area :descricao, rows: 5, class: "form-control", id:"descricao" %>
	    </div>
	    <div class="form-group">
        <%= label_tag nil, "Usar Descrição da Wikipedia?" %>
        <%= check_box_tag :usa_wiki, true, nil, id: "usa-wiki" %>
      </div>
	    <hr>
	    <%= f.submit "Enviar", class: "btn btn-large btn-primary" %>
	    <p></p>
	  <% end %>
	</div>
</div>

app/views/generos/_genero.html.erb
<tr>
  <td><%= link_to genero.nome, genero %></td>
  <td><small> <%= truncate(genero.descricao,{ :length => 50, omission: '... (continua)' }) %> </small></td>
  <% if admin? %>
      <td>
       <%= link_to "Excluir", genero, method: :delete, data: { confirm: 'Você tem certeza?' } %> |
       <%= link_to "Editar", edit_genero_path(genero) %>
      </td>
  <% end %>
</tr>

app/views/generos/_itens_relacionados.html.erb
<% if itens.any? %>
  <h4>Itens relacionados (<%= itens.size.count %>)</h4>
  <hr>
  <!-- Loop para cada item do usuário -->
  <% @count = 1 %>
  <% @itens.each do |item| %>
    <% if @count % 3 == 0 %>
      <div class="row">
    <% end %>
    <div class="col-md-4 text-center">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
              <h4> <%= link_to item.nome_ptbr, item_path(item) %> </h4>
          </h3>
        </div>
        <div class="panel-body">
            <label> <%= truncate(item.descricao,{ :length => 100, omission: '...' }) %> </label>
        </div>
      </div>
    </div>
    <% if @count % 3 == 0 %>
      </div>
      <hr>
    <% end %>
    <% @count = @count + 1 %>
  <% end %>
<% end %>

app/views/generos/edit.html.erb
<%= render "compartilhado/breadcrumb", pag: @genero.nome.titleize %>

<h1>Editando gênero</h1>

<%= render 'edit_form' %>

<%= link_to 'Mostrar', @genero %> 

app/views/generos/index.html.erb
<%= render "compartilhado/breadcrumb", pag: "Todos os Gêneros" %>

<h2>Todos os Gêneros! (<%= @generos_count %>)</h2>

<div class="row">
	<div class="col-md-2">
		<%= form_tag( { controller: :generos, action: :index }, method: "get") do %>
		  <div class="inner-addon right-addon">
		      <i class="glyphicon glyphicon-search"></i>
		      <%= text_field_tag(:q, nil, class: "form-control", height:"15", width:"15") %>
		  </div>
		<% end %>
	</div>
</div>
<hr>
<% if signed_in? %>
<p><h5>Não achou o gênero que procurava? <%= link_to 'Crie um novo gênero', new_genero_path %></h5></p>
<% end %>

<table class="table table-hover">
		<tr class="info">                      
		<th><%= sortable "nome" %></th>
		<th><%= sortable "descricao", "Descrição" %></th>
		<% if admin? %>
			<th><%= sortable "acoes", "Ações" %></th>
		<% end %>
	</tr>
  <%= render @generos %>
</table>

<%= will_paginate @generos, :previous_label => " << Anterior", :next_label => "Proximo >>", renderer: BootstrapPagination::Rails %>

app/views/generos/new.html.erb
<%= render "compartilhado/breadcrumb", pag: "Novo Gênero" %>

<h1>Novo Gênero</h1>

<%= render 'form' %>

app/views/generos/show.html.erb
<%= render "compartilhado/breadcrumb", pag: @genero.nome.titleize %>

<div class="row">
  <aside class="col-sm-3">
    <section>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
              <h4> <%= @genero.nome %> </h4>
          </h3>
        </div>
        <div class="panel-body">
            <label> <%= @genero.try(:descricao)%> </label>
        </div>
      </div>
      <% if signed_in? %>
        <%= render partial: "compartilhado/nova_flag", locals: { flagavel: @genero, id: "flag_genero" } %>
      </br></br>
      <% end %>
      <% if admin? %>
        <%= link_to "Excluir", @genero, method: :delete, data: { confirm: 'Você tem certeza?' } %> |
      <% end %>
      <% if signed_in? %>
        <%= link_to 'Editar', edit_genero_path(@genero) %>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render "itens_relacionados" , itens: @itens %>
  </div>
</div>
<div class="row">
  <div class="col-md-4"></div>
  <%= will_paginate @itens, :previous_label => " << Anterior", :next_label => "Proximo >>", renderer: BootstrapPagination::Rails %>
</div>