config/routes.rb
Rails.application.routes.draw do

  root 'suggestions#index'

    
    match '/usuarios/set_admin/:id', to: 'usuarios#set_admin', via: 'patch', as: 'set_usuario_admin'
    match '/reset_password', to: 'usuarios#reset_password', via: 'get'
    match '/send_reset_password', to: 'usuarios#send_reset_password', via: 'post'
    match '/confirm_account/:id', to: 'usuarios#confirm_account', via: 'get'
    match '/usuarios/:id/edit_preferences', to: 'usuarios#edit_preferences', via: 'get', as: 'edit_preferences'
    match '/usuarios/:id/update_preferences:id', to: 'usuarios#update_preferences', via: 'patch'
    match '/usuarios/:id/edit_password', to: 'usuarios#edit_password', via: 'get', as: 'edit_password'
    match '/usuarios/:id/update_password', to: 'usuarios#update_password', via: 'patch'
    match '/signup', to: 'usuarios#new', via: 'get'

    match '/signin',  to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    match '/collaborative_recommendation', to: 'itens#collaborative_recommendation', via: 'get'
    match '/refresh_item_img/:id', to: 'itens#refresh_item_img', via: 'get'
    match '/content_recommendation/:id', to: 'itens#content_recommendation', via: 'get'

    match '/avaliacoes', to: 'avaliacoes#create_update', via: 'post'

    match '/generalizacoes/destroy_all', to: 'generalizacoes#destroy_all', via: 'post'

    match 'auth/:provider/callback', to: 'sessions#create_facebook', via: 'get'
    match 'auth/failure', to: redirect('/'), via: 'get'

    match '/sobre', to: 'suggestions#sobre', via: 'get'
    match '/privacidade', to: 'suggestions#privacidade', via: 'get'
    match '/termos', to: 'suggestions#termos', via: 'get'
    match '/contato', to: 'suggestions#contato', via: 'get'
    match '/suggestions/enviar_contato', to: 'suggestions#enviar_contato', via: 'post'

    resources :relacoes, only: [:create, :destroy]

    resources :generos, :categorias, :generalizacoes, :itens, :usuarios, :flags

    resources :avaliacoes, only: :update

    resources :comentarios, only: [:create, :destroy, :edit, :update, :show]

    resources :sessions, only: [:new, :create, :destroy]

    resources :usuarios do
      member do # poderia ser collection
        get :seguindo, :seguidores
      end
    end

  match ':controller(/:action(/:id(.:format)))', via: 'get'
  

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base

	validates_presence_of :comentario, :usuario_id, :item_id, message: "deve ser preenchido!"

	belongs_to :usuario
	belongs_to :item

	has_many :flags, as: :flagavel, dependent: :destroy

	def get_name 
  	"Comentário #{self.id}"
  end

end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [ :destroy, :edit, :update, :show ]
  before_action :usuario_logado?, only: [ :create, :destroy, :new ]

  # GET /comentarios/1/edit
  def edit
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        flash[:success] = "Comentário foi atualizado com sucesso!"
        format.html { redirect_to item_path(@comentario.item) }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = current_user.comentarios.build(comentario_params)
    if @comentario.save
      flash[:success] = "Comentário salvo!"
    else
      flash[:danger] = "Comentário não foi salvo!"
    end
    redirect_to item_path(@comentario.item)
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    if @comentario.destroy
      flash[:success] = "Comentário excluido com sucesso!"
    else
      flash[:danger] = "Comentário não foi excluido corretamente!"
    end
      redirect_to item_path(@comentario.item)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:item_id, :comentario)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <%= render 'compartilhado/mensagens_erro', object: f.object %>
<% end %>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@comentario) do |f| %>
      <div class="form-group">
      <%= f.label :comentario, "Comentario" %>
      <%= f.text_area :comentario, class: "form-control" %>
      </div>
      <hr>
      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
      <p></p>
    <% end %>
  </div>
</div>

app/views/comentarios/_todos_comentarios.html.erb
<% if @comentarios.any? %>
  <!-- Loop para cada comentario do item -->
  <% @comentarios.each do |comentario| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span> <%= link_to comentario.usuario.username, usuario_path(comentario.usuario) %></span>
          <small>  
            <span class="glyphicon glyphicon-thumbs-up"><%= comentario.like %></span>
            <span class="glyphicon glyphicon-thumbs-down"><%= comentario.dislike %></span>
            <%= render partial: "compartilhado/nova_flag", locals: { flagavel: comentario, id: "flag_comentario" } unless !signed_in? %>
            <span>
              <% if is_admin? or current_user == comentario.usuario %>
                <%= link_to "deletar", comentario, method: :delete %>
                <% #link_to "editar", edit_comentario_path(comentario) %>
              <% end %> 
            </span>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        <%= comentario.comentario %>
      </div>
    </div>
  <% end %>
<% end %>
<%= will_paginate @comentarios, :previous_label => " << Anterior", :next_label => "Proximo >>", renderer: BootstrapPagination::Rails %>

app/views/comentarios/edit.html.erb
<%= render "compartilhado/breadcrumb", pag: "Editando Comentário" %>

<h1>Editando comentario</h1>

<%= render 'form' %>

app/views/comentarios/index.html.erb
<%= render "compartilhado/breadcrumb", pag: "Todos os Comentários" %>

<h1>Listando Comentarios</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= link_to 'Mostrar', comentario %></td>
        <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Excluir', comentario, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Comentario', new_comentario_path %>

app/views/comentarios/show.html.erb
<%= render "compartilhado/breadcrumb", pag: "Comentário #{@comentario.id}" %>

<div class="row">
  <aside class="col-sm-3">
    <section>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
              <h4> <%= @comentario.usuario.get_name.titleize %> </h4>
          </h3>
        </div>
        <div class="panel-body">
            <p><label>Usuário: </label> <%= link_to @comentario.usuario.get_name, usuario_path(@comentario.usuario) %></p>
            <p><label>Item: </label> <%= link_to @comentario.item.get_name, item_path(@comentario.item) %></p>
            <p><label>Like: </label> <%=  @comentario.like.to_s %></p>
            <p><label>Dislike: </label> <%= @comentario.like.to_s %></p>
            <p><label>Criado em: </label> <%= @comentario.created_at.to_s(:db) %></p>
            <p><label>Modificado em: </label> <%= @comentario.updated_at.to_s(:db) %></p>
        </div>
      </div>
      <% if admin? or current_user?(@comentario.usuario) %>
        <%= link_to "Excluir", @comentario, method: :delete %> |
        <%= link_to "Editar", edit_comentario_path(@comentario) %> |
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <section>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
              <h4> Comentário </h4>
          </h3>
        </div>
        <div class="panel-body">
          <p><%= @comentario.comentario%></p>
        </div>
      </div>
    </section>
  </div>
</div>