config/routes.rb
Rails.application.routes.draw do

  root 'suggestions#index'

    
    match '/usuarios/set_admin/:id', to: 'usuarios#set_admin', via: 'patch', as: 'set_usuario_admin'
    match '/reset_password', to: 'usuarios#reset_password', via: 'get'
    match '/send_reset_password', to: 'usuarios#send_reset_password', via: 'post'
    match '/confirm_account/:id', to: 'usuarios#confirm_account', via: 'get'
    match '/usuarios/:id/edit_preferences', to: 'usuarios#edit_preferences', via: 'get', as: 'edit_preferences'
    match '/usuarios/:id/update_preferences:id', to: 'usuarios#update_preferences', via: 'patch'
    match '/usuarios/:id/edit_password', to: 'usuarios#edit_password', via: 'get', as: 'edit_password'
    match '/usuarios/:id/update_password', to: 'usuarios#update_password', via: 'patch'
    match '/signup', to: 'usuarios#new', via: 'get'

    match '/signin',  to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    match '/collaborative_recommendation', to: 'itens#collaborative_recommendation', via: 'get'
    match '/refresh_item_img/:id', to: 'itens#refresh_item_img', via: 'get'
    match '/content_recommendation/:id', to: 'itens#content_recommendation', via: 'get'

    match '/avaliacoes', to: 'avaliacoes#create_update', via: 'post'

    match '/generalizacoes/destroy_all', to: 'generalizacoes#destroy_all', via: 'post'

    match 'auth/:provider/callback', to: 'sessions#create_facebook', via: 'get'
    match 'auth/failure', to: redirect('/'), via: 'get'

    match '/sobre', to: 'suggestions#sobre', via: 'get'
    match '/privacidade', to: 'suggestions#privacidade', via: 'get'
    match '/termos', to: 'suggestions#termos', via: 'get'
    match '/contato', to: 'suggestions#contato', via: 'get'
    match '/suggestions/enviar_contato', to: 'suggestions#enviar_contato', via: 'post'

    resources :relacoes, only: [:create, :destroy]

    resources :generos, :categorias, :generalizacoes, :itens, :usuarios, :flags

    resources :avaliacoes, only: :update

    resources :comentarios, only: [:create, :destroy, :edit, :update, :show]

    resources :sessions, only: [:new, :create, :destroy]

    resources :usuarios do
      member do # poderia ser collection
        get :seguindo, :seguidores
      end
    end

  match ':controller(/:action(/:id(.:format)))', via: 'get'
  

end

app/controllers/itens_controller.rb
class ItensController < ApplicationController
  helper_method :sort_coluna, :sort_direcao
  before_action :set_item, only: [:show, :edit, :update, :destroy, :content_recommendation, :refresh_item_img]
  before_action :usuario_admin, only: [:destroy] # Verifica se é o usuário admin.

  # GET /itens
  # GET /itens.json
  def index

    @q = params[:q]

    if @q
      @search = Item.search do
        keywords params[:q]
        paginate(page: params[:page], :per_page => 30)
      end
      @itens = @search.results
      @avaliacoes = avaliacoes
    else
      #@itens = Item.joins(:avaliacoes).group("avaliacoes.item_id").order("sum(avaliacoes.avaliacao) desc").paginate(page: params[:page], :per_page => 30)
      @itens = Item.order(sort_coluna + " " + sort_direcao).paginate(page: params[:page], :per_page => 30).includes(:categoria)
      @avaliacoes = avaliacoes
    end

    @itens_count = @itens.size
    gon.usuario_logado = signed_in?
    
  end

  # GET /itens/1
  # GET /itens/1.json
  def show

    # Atributos do item em questão
    @comentarios = @item.comentarios.paginate(page: params[:comentario_page], :per_page => 15).order(created_at: :desc).includes(:usuario)
    @avaliacoes = @item.avaliacoes.paginate(page: params[:avaliacao_page], :per_page => 15).order(created_at: :desc).includes(:usuario)
    @avaliacoes_count = { positivas: @item.avaliacoes.where("avaliacao = ?", true).count, negativas: @item.avaliacoes.where("avaliacao = ?", false).count }

    gon.usuario_logado = signed_in?
    gon.item_id = @item.id

    @item.update(last_visited: Time.now)

  end

  # GET /itens/new
  def new
    @item = Item.new
  end

  # GET /itens/1/edit
  def edit
  end

  def content_recommendation
  # GET /itens/1
  
    start_t = Time.now

    @itens_recomendados = []
  
    if @item.generos.size != 0

      c_recommendations = ContentRecommendationService.new(@item, current_user)

      @itens_recomendados = c_recommendations.recommend
    end

    finish_t = Time.now
    #puts "Tempo para realizar todo o processo: " + (finish_t - start_t).to_s + "segundos"
  
    respond_to do |format|
       format.js
    end
  
  end

  def refresh_item_img
    @url = @item.get_image_url
    #puts "url: #{@url}"
    respond_to do |format|
      format.js
    end
  end

  # GET /itens/
  def collaborative_recommendation

    start_t = Time.now

    @livros = Hash.new
    @filmes = Hash.new
    @jogos = Hash.new
    @musicas = Hash.new

    # Numero de avaliações feitas pelo usuário logado
    @num_avaliacoes = current_user.avaliacoes.size

    if @num_avaliacoes >= GlobalConstants::NUM_AVALIACOES

      c_recommendations = CollaborativeRecommendationService.new(current_user)

      recommendations = c_recommendations.recommend

      recommendations = recommendations.sort_by { |item_id, nota| nota }.reverse.take 200

      recommendations.each do |item_id, nota|
        
        if nota >= 0
          item = Item.find(item_id)

          if item.book?
            @livros[nota] = item
          elsif item.film?
            @filmes[nota] = item
          elsif item.game?
            @jogos[nota] = item
          elsif item.music?
            @musicas[nota] = item
          end
        end 
      end

    end

    qtde_recomendacao = current_user.max_rec_colaborativa

    @livros  = @livros.take(qtde_recomendacao)
    @filmes  = @filmes.take(qtde_recomendacao)
    @jogos   = @jogos.take(qtde_recomendacao)
    @musicas = @musicas.take(qtde_recomendacao)

    finish_t = Time.now
    #puts "Tempo para realizar todo o processo: " + (finish_t - start_t).to_s + "segundos"

  end

  # POST /itens
  # POST /itens.json
  def create
    @item = Item.new(item_params)

    if params.has_key?(:usa_wiki)
      @item.descricao = Utils::descricao_wiki(@item.get_name)
      if @item.descricao.nil?
        flash.now[:danger] = "Não foi possível buscar a descrição do Wikipédia"
        render :new
        return
      end
    end

    respond_to do |format|
      if @item.save
        flash[:success] = "Item foi criado com sucesso!"
        format.html { redirect_to @item }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itens/1
  # PATCH/PUT /itens/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        flash[:success] = "O item foi editado com sucesso!"
        format.html { redirect_to @item}
        format.json { render :show, status: :ok, location: @item }
      else
        flash.now[:danger] = "O item não foi editado com sucesso!"
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itens/1
  # DELETE /itens/1.json
  def destroy
    @item.destroy
    flash[:success] = "Item foi excluído com sucesso!"
    respond_to do |format|
      format.html { redirect_to itens_url }
      format.json { head :no_content }
    end
  end

  def search
    @q = params[:q]
    @search = Item.search do
      keywords params[:q]
      paginate(page: params[:page], :per_page => 30)
    end

    @itens = @search.results
    @avaliacoes = avaliacoes

  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:categoria_id, :nome_ptbr, :nome_en, :descricao)
    end

    def sort_coluna
      Item.column_names.include?(params[:coluna]) ? params[:coluna] : "id"
    end

    def sort_direcao
      %w[asc desc].include?(params[:direcao]) ? params[:direcao] : "asc"
    end

    def avaliacoes
      @avaliacoes = Hash.new
      @itens.each do |item|
        @avaliacoes[item.id] = [Avaliacao.where('item_id = ? AND avaliacao = ?', item.id, false).count, Avaliacao.where('item_id = ? AND avaliacao = ?', item.id, true).count]
      end
      return @avaliacoes
    end
end

app/helpers/itens_helper.rb
module ItensHelper

	def formata_str_parecidos(item)
		if item.film?
			"Filmes"
		elsif item.game?
			"Jogos"
		elsif item.music?
			"Artistas"
		elsif item.book?
			"Livros"
		end
	end

	def label_type(item)

		if item.categoria_id == 1
      "label label-primary"
    elsif item.categoria_id == 2
      "label label-success"
    elsif item.categoria_id == 3
      "label label-info"
    elsif item.categoria_id == 4
      "label label-warning"
    end
	end
end

app/views/itens/_avaliacoes.html.erb
<% if @avaliacoes.any? %>
  <!-- Loop para cada avaliacao do usuário -->
  <ul class="list-group">
  <% @avaliacoes.each do |avaliacao| %>
      <li class="list-group-item">
        <img src=<%= avaliacao.usuario.image %> alt="profile pic" height="42" width="42" class="img-rounded">
        <%= link_to avaliacao.usuario.username, usuario_path(avaliacao.usuario) %>
        <% if avaliacao.avaliacao %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
        <% else %>
          <span class="glyphicon glyphicon-thumbs-down"></span>
        <% end %>
      </li>
  <% end %>
  </ul>
<% else %>
  <p> <strong><%= @item.get_name.titleize %></strong> ainda não possui avaliações </p>
<% end %>
<%= will_paginate @avaliacoes, :previous_label => " << Anterior", :next_label => "Proximo >>", renderer: BootstrapPagination::Rails, param_name: 'avaliacao_page'  %>

app/views/itens/_comentarios.html.erb
<% if @comentarios.any? %>
  <!-- Loop para cada comentario do item -->
  <% @comentarios.each do |comentario| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span> <%= link_to comentario.usuario.username, usuario_path(comentario.usuario) %></span>
          <small>  
            <span class="glyphicon glyphicon-thumbs-up"><%= comentario.like %></span>
            <span class="glyphicon glyphicon-thumbs-down"><%= comentario.dislike %></span>
            <%= render partial: "compartilhado/nova_flag", locals: { flagavel: comentario, id: "flag_comentario" } unless !signed_in? %>
            <span>
              <% if admin? or current_user?(comentario.usuario) %>
                <%= link_to "deletar", comentario, method: :delete, data: { confirm: 'Você tem certeza?' } %>
              <% end %> 
            </span>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        <%= comentario.comentario %>
      </div>
    </div>
  <% end %>
<% else %>
  <p> <strong><%= @item.get_name.titleize %></strong> ainda não possui comentários </p>
<% end %>
<%= will_paginate @comentarios, :previous_label => " << Anterior", :next_label => "Proximo >>", renderer: BootstrapPagination::Rails, param_name: 'comentario_page' %>

app/views/itens/_content_recommendation.html.erb
<% if itens.blank? %>
	<h3><%= "Ainda não há itens parecidos" %></h3>
	<h4><%= "Você pode ajudar adicionando um gênero ao item" %></h4>
	<button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#genero">
		Adicionar Tags
	</button>
<% else %>
	<h3><%= "Itens parecidos:" %></h3>
<% end %>
<ul class="list-group">
	<% itens.each do |id, nota| %>
		<li class="list-group-item">
			<%= link_to Item.find(id).get_name.titleize, item_path(id) %> <%= nota %>
		</li>
	<% end %>
</ul>

app/views/itens/_edit_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@item) do |f| %>
      <%= render 'compartilhado/mensagens_erro', object: f.object %>
      <div class="form-group">
      <%= f.label :categoria_id, "Categoria" %>
      <%= f.collection_select(:categoria_id, Categoria.order(:descricao), :id, :descricao, {}, { class: "form-control", disabled: !admin? }) %>
      </div>
      <div class="form-group">  
      <%= f.label :nome_ptbr, "Nome em Português" %>
      <%= f.text_field :nome_ptbr, class: "form-control", disabled: !admin? %>
      </div>
      <div class="form-group">
      <%= f.label :nome_en, "Nome em Inglês" %>
      <%= f.text_field :nome_en, class: "form-control", disabled: !admin? %>
      </div>
      <div class="form-group">
      <%= f.label :descricao, "Descrição" %>
      <%= f.text_area :descricao, rows: 6, class: "form-control" %>
      </div>
      <hr>
      <%= f.submit "Enviar", class: "btn btn-large btn-primary" %>
      <hr>
      NOTA: O mau uso do sistema Suggest Me resultará na expulsão do usuário do site.
    <% end %>
  </div>
</div>
<%= link_to "Voltar", item_path(@item) %>

app/views/itens/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@item) do |f| %>
      <%= render 'compartilhado/mensagens_erro', object: f.object %>
      <div class="form-group">
        <%= f.label :categoria_id, "Categoria" %>
        <%= f.collection_select(:categoria_id, Categoria.order(:descricao), :id, :descricao, class: "form-control" ) %>
      </div>
      <div class="form-group">
        <%= f.label :nome_ptbr, "Nome em Português" %>
        <%= f.text_field :nome_ptbr, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :nome_en, "Nome em Inglês" %>
        <%= f.text_field :nome_en, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :descricao, "Descrição" %>
        <%= f.text_area :descricao, rows: 5, class: "form-control", id: "descricao" %>
      </div>
      <div class="form-group">
        <%= label_tag nil, "Usar Descrição da Wikipedia?" %>
        <%= check_box_tag :usa_wiki, true, nil, id: "usa-wiki" %>
      </div>
      <hr>
      <%= f.submit "Enviar", class: "btn btn-large btn-primary" %>
      <p></p>
    <% end %>
  </div>
</div>

app/views/itens/_new_generalizacao.html.erb
<!-- Modal Novo Genero -->
<div class="modal fade" id="genero" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"> <%= @item.get_name.titleize %></h4>
      </div>
      <%= form_for item.generalizacoes.new(item_id: @item.id) do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.hidden_field :item_id %>
            <%= f.label :genero_id, "Gênero" %>
            <%= f.collection_select(:genero_id, Genero.order(:nome), :id, :nome, class: "form-control" ) %>
          </div>
        </div>
        <div class="modal-footer">
          <%= link_to "Criar novo gênero", new_genero_path %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <button type="submit" name= "commit" class="btn btn-primary">Salvar</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/itens/content_recommendation.js.erb
$("#content-recommendation").html("<%= j (render 'content_recommendation', itens: @itens_recomendados ) %>");

app/views/itens/edit.html.erb
<%= render "compartilhado/breadcrumb", pag: @item.get_name.titleize %>

<h1>Editando item</h1>

<%= render 'edit_form' %>

app/views/itens/index.html.erb
<% provide(:title, 'Todos os Itens') %>

<%= render "compartilhado/breadcrumb", pag: "Todos os Itens" %>

<h2>Todos os Itens! (<%= @itens_count %>)</h2>

<% if signed_in? %>
		<h5> Não achou o item que procurava? <%= link_to "Crie um novo item!", new_item_path %></h3>
<% end %>

<table class="table table-hover">
	<tr class="info">                      
		<th><%= sortable "nome_ptbr", "Nome"%></th>
		<th><%= sortable "descricao", "Descrição" %></th>
		<th><%= sortable "avaliacao", "Avaliação" %></th>
		<th><%= sortable "categoria_id", "Categoria"%></th>
		<% if admin? %>
			<th><%= sortable "acoes", "Ações" %></th>
		<% end %>
	</tr>
  <%= render @itens %>
</table>

<%= will_paginate @itens, :previous_label => " << Anterior", :next_label => "Proximo >>", renderer: BootstrapPagination::Rails %>

app/views/itens/new.html.erb
<%= render "compartilhado/breadcrumb", pag: "Novo Item" %>

<h1>Cadastro de novo Item</h1>

<%= render 'form' %>

app/views/itens/recomendacao.html.erb
    <%= render "compartilhado/breadcrumb", pag: "Recomendações" %>

    <% if @num_avaliacoes <= GlobalConstants::NUM_AVALIACOES %>

      <h3><span class="label label-warning">Opss</span> Não foi possível realizar as recomendações </h3>

      <p>Você precisa ter mais que <%= GlobalConstants::NUM_AVALIACOES %> avaliações no total.
         Comece por <%= link_to "aqui", itens_path %>!
      </p>

    <% else %>
    
      <ul id="collaborative-recommendation" class = "nav nav-tabs" >
        <li>
          <a href="#filmes" data-toggle = "tab"><span class="glyphicon glyphicon-film"></span> Filmes </a>
        </li>
        <li>
          <a href="#musicas" data-toggle = "tab"><span class="glyphicon glyphicon-music"></span> Musicas</a>
        </li>
        <li>
          <a href="#jogos" data-toggle = "tab"><span class="glyphicon glyphicon-tower"></span> Jogos</a>
        </li>
        <li>
          <a href="#livros" data-toggle = "tab"><span class="glyphicon glyphicon-book"></span>Livros</a>
        </li>
      </ul>
      <!-- Filmes -->
      <div class = "tab-content">
        <!-- Filmes -->
        <div class = "tab-pane fade" id="filmes">
          <div class="row">
            <div class="panel panel-default">
              <div class="panel-heading"><h1><span class ="glyphicon glyphicon-film"></span> Filmes</h1></div>
              <div class="panel-body">
                <% @count = 1 %>
                <% @filmes.each do |key, filme| %>
                  <% if @count % 3 == 0 %>
                    <div class="row">
                  <% end %>
                  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center">
                    <div class= "thumbnail align-center">
                      <div class = "caption">
                        <h3><%= filme.nome_ptbr %></h3><%= key %>
                        <p><%= truncate(filme.descricao,{ :length => 30, omission: '...' }) %></p>
                        <p><%= link_to "Veja Mais", item_path(filme) %> &raquo;</p>
                      </div>
                    </div>
                  </div>
                  <% if @count % 3 == 0 %>
                    </div>
                    <hr>
                  <% end %>
                  <% @count = @count + 1 %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <!-- Musicas -->
        <div class = "tab-pane fade" id="musicas">
            <div class="row">
              <div class="panel panel-default">
                <div class="panel-heading"><h1><span class ="glyphicon glyphicon-music"></span> Musicas</h1></div>
                <div class="panel-body">
                  <% @count = 1 %>
                  <% @musicas.each do |key, musica| %>
                    <% if @count % 3 == 0 %>
                      <div class="row">
                    <% end %>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center">
                      <div class= "thumbnail align-center">
                        <div class = "caption">
                          <h3><%= musica.nome_ptbr %></h3><%= key %>
                          <p><%= truncate(musica.descricao,{ :length => 30, omission: '...' }) %></p>
                          <p><%= link_to "Veja Mais", item_path(musica) %> &raquo;</p>
                        </div>
                      </div>
                    </div>
                    <% if @count % 3 == 0 %>
                      </div>
                      <hr>
                    <% end %>
                    <% @count = @count + 1 %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <!-- Jogos -->
        <div class = "tab-pane fade" id="jogos">
            <div class="row">
              <div class="panel panel-default">
                <div class="panel-heading"><h1><span class ="glyphicon glyphicon-tower"></span> Jogos</h1></div>
                <div class="panel-body">
                  <% @count = 1 %>
                  <% @jogos.each do |key, jogo| %>
                    <% if @count % 3 == 0 %>
                      <div class="row">
                    <% end %>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center">
                      <div class= "thumbnail align-center">
                        <div class = "caption">
                          <h3><%= jogo.nome_ptbr %></h3><%= key %>
                          <p><%= truncate(jogo.descricao,{ :length => 30, omission: '...' }) %></p>
                          <p><%= link_to "Veja Mais", item_path(jogo) %> &raquo;</p>
                        </div>
                      </div>
                    </div>
                    <% if @count % 3 == 0 %>
                      </div>
                      <hr>
                    <% end %>
                    <% @count = @count + 1 %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <!-- Livros -->
        <div class = "tab-pane fade" id="livros">
            <div class="row">
              <div class="panel panel-default">
                <div class="panel-heading"><h1><span class ="glyphicon glyphicon-book"></span> Livros</h1></div>
                <div class="panel-body">
                  <% @count = 1 %>
                  <% @livros.each do |key, livro| %>
                    <% if @count % 3 == 0 %>
                      <div class="row">
                    <% end %>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center">
                      <div class= "thumbnail align-center">
                        <div class = "caption">
                          <h3><%= livro.nome_ptbr %></h3><%= key %>
                          <p><%= truncate(livro.descricao,{ :length => 30, omission: '...' }) %></p>
                          <p><%= link_to "Veja Mais", item_path(livro) %> &raquo;</p>
                        </div>
                      </div>
                    </div>
                    <% if @count % 3 == 0 %>
                      </div>
                      <hr>
                    <% end %>
                    <% @count = @count + 1 %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      </div>

    <% end %>

app/views/itens/recommendations.js.erb
$("#content-recommendation").html("<%= j (render 'content_recommendation', itens: @itens_recomendados ) %>")

app/views/itens/refresh_item_img.js.erb
$("#item-img").html('<a href="#"><img size: "280x160" src=<%= @url %> class="img-thumbnail" /><a>');

app/views/itens/show.html.erb
<% provide(:title, @item) %>

<%= render "compartilhado/breadcrumb", pag: @item.get_name.titleize %>

<!-- Row Principal -->
<div class="row">
  <!-- Aside -->
  <aside class="col-sm-3">
    <div class="row">
      <div id="content" class="col-md-offset-1 col-md-11">
        <section>
          <div id="item-img">
            <a href="#"><img size: "280x160" src=<%= @item.get_image_url %> class="img-thumbnail" /></a>
          </div>
          <hr>
          <button type="button" class="btn btn-primary btn-md" id="like"> <%= @avaliacoes_count[:positivas] %>
            <span class="glyphicon glyphicon-thumbs-up"></span>
          </button>
          <button type="button" class="btn btn-danger btn-md" id="dislike"> <%= @avaliacoes_count[:negativas] %>
            <span class="glyphicon glyphicon-thumbs-down"></span>
          </button>
          <% if signed_in? %>
            <%= form_for current_user.avaliacoes.build(item_id: @item.id) do |f| %>
              <%= f.hidden_field :item_id %>
              <%= f.hidden_field :avaliacao, id: "hidden_tipo" %>
              <%= f.submit "Like!", { style: "display: none", id: "submit"} %>
            <% end %>
          <% end %>
          <hr>
          <label>Categoria:</label> <%= link_to @item.categoria.descricao, categoria_path(@item.categoria) %> </br>
    			<label>Nome: </label> <%= @item.try(:nome_ptbr).try(:titleize) %> </br>
          <small><label>Inglês: </label> <%= @item.try(:nome_en).try(:titleize) %></small> </br>
    			<label>Descrição: </label> <%= @item.descricao %> </br>
          <label>Gêneros: </label> 
            <% unless @item.generos.empty? %>
              <% @item.generos.group("generos.id").each do |genero| %>
                <%= link_to genero.nome + ',', genero_path(genero) %> 
                <% if admin? %>
                  <%= form_tag('/generalizacoes/destroy_all', method: :post) do %>
                    <%= hidden_field_tag :item_id, @item.id %>
                    <%= hidden_field_tag :genero_id, genero.id %>
                    <%= submit_tag 'x', class: "btn btn-danger btn-xs"%>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% if signed_in? %>
            <!-- Button trigger modal Generos-->
            <br>
            <button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#genero">
              Adicionar Tags
            </button>
            <br>
              <%= render partial: "new_generalizacao", locals: { item: @item } %>
          <% end %>
          </br>
          <label>Mais: </label> <%= link_to 'Wikipedia', @item.wiki_link %> <br><br>
          <%= render partial: "compartilhado/nova_flag", locals: { flagavel: @item, id: "flag_item" } if signed_in? %>
          </br></br>
          <% if signed_in? %>
            <%= link_to 'Editar', edit_item_path(@item) %> |
          <% end %>
          <% if admin?%>
            <%= link_to 'Excluir', item_path(@item), method: :delete, data: { confirm: 'Você tem certeza?' } %>
          <% end %>
    			<hr>
        </section>
      </div>
    </div>
  </aside>
  <!-- Content -->
    <div class="col-md-6">
      <div class="row">
        <div id="content" class="col-md-offset-1 col-md-11 content content">
        <% if signed_in? %>
            <%= form_for current_user.comentarios.build(item_id: @item.id) do |f| %>
              <%= render 'compartilhado/mensagens_erro', object: f.object %>
              <%= f.hidden_field :item_id %>
              <div class="field">
                <%= f.text_area :comentario, placeholder: "Escreva seu Comentario...", rows: "4" %>
              </div>
              <div class="col-md-4.5 col-md-offset-8">
                <%= f.submit "Comentar!", class: "btn btn-large btn-primary" %>
              </div>
            <% end %>
        <% else %>
          <div class="well">
            <p>Deixe um comentário. <%= link_to "Faça login no Suggest Me", signin_path %> ou <%= link_to "registre-se.", signup_path %>
            </p>
          </div>
        <% end %>
        <hr>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
          <li class="active"><a href="#comentario" data-toggle="tab">Comentários <span class="badge"><%= @comentarios.count %></span></a></li>
          <li><a href="#avaliacao" data-toggle="tab">Avaliações <span class="badge"><%= @avaliacoes.count %></span></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane active" id="comentario">
            <%= render "comentarios", comentarios: @comentarios %>
          </div>
          <div class="tab-pane" id="avaliacao">
            <%= render "avaliacoes", avaliacoes: @avaliacoes %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Artistas Parecidos -->
  <div id="content-recommendation" class="col-sm-3">
    <!-- Ajax vai aqui -->
    <h3>Carregando Recomendações</h3>
    <%= image_tag "ajax-loader.gif" %>
  </div>
</div>