config/routes.rb
Rails.application.routes.draw do

  root 'suggestions#index'

    
    match '/usuarios/set_admin/:id', to: 'usuarios#set_admin', via: 'patch', as: 'set_usuario_admin'
    match '/reset_password', to: 'usuarios#reset_password', via: 'get'
    match '/send_reset_password', to: 'usuarios#send_reset_password', via: 'post'
    match '/confirm_account/:id', to: 'usuarios#confirm_account', via: 'get'
    match '/usuarios/:id/edit_preferences', to: 'usuarios#edit_preferences', via: 'get', as: 'edit_preferences'
    match '/usuarios/:id/update_preferences:id', to: 'usuarios#update_preferences', via: 'patch'
    match '/usuarios/:id/edit_password', to: 'usuarios#edit_password', via: 'get', as: 'edit_password'
    match '/usuarios/:id/update_password', to: 'usuarios#update_password', via: 'patch'
    match '/signup', to: 'usuarios#new', via: 'get'

    match '/signin',  to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    match '/collaborative_recommendation', to: 'itens#collaborative_recommendation', via: 'get'
    match '/refresh_item_img/:id', to: 'itens#refresh_item_img', via: 'get'
    match '/content_recommendation/:id', to: 'itens#content_recommendation', via: 'get'

    match '/avaliacoes', to: 'avaliacoes#create_update', via: 'post'

    match '/generalizacoes/destroy_all', to: 'generalizacoes#destroy_all', via: 'post'

    match 'auth/:provider/callback', to: 'sessions#create_facebook', via: 'get'
    match 'auth/failure', to: redirect('/'), via: 'get'

    match '/sobre', to: 'suggestions#sobre', via: 'get'
    match '/privacidade', to: 'suggestions#privacidade', via: 'get'
    match '/termos', to: 'suggestions#termos', via: 'get'
    match '/contato', to: 'suggestions#contato', via: 'get'
    match '/suggestions/enviar_contato', to: 'suggestions#enviar_contato', via: 'post'

    resources :relacoes, only: [:create, :destroy]

    resources :generos, :categorias, :generalizacoes, :itens, :usuarios, :flags

    resources :avaliacoes, only: :update

    resources :comentarios, only: [:create, :destroy, :edit, :update, :show]

    resources :sessions, only: [:new, :create, :destroy]

    resources :usuarios do
      member do # poderia ser collection
        get :seguindo, :seguidores
      end
    end

  match ':controller(/:action(/:id(.:format)))', via: 'get'
  

end

app/views/layouts/_footer.html.erb
<!-- Footer! -->
<div class="container">
  <hr>
  <footer>
    <p class="text-center"> Desenvolvido por Vitor Rodrigo Vezani</p>
    <p class="text-center"><small>&copy; Suggest Me. 2014</small></p>
  </footer>
</div> 
<!-- /Footer -->

app/views/layouts/_header.html.erb
<!-- Navigation Bar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Botão de tela estreita -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Suggest Me", root_path , class: "navbar-brand" %>
    </div>
    <!-- /Botão de tela estreita -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse">
      <!-- Botões do navbar -->
      <ul class="nav navbar-nav">
        <li>
          <%= form_tag( { controller: "itens", action: "index"}, method: "get", class: "navbar-form navbar-right") do %>
            <div class="inner-addon right-addon">
                <i class="glyphicon glyphicon-search"></i>
                <%= text_field_tag(:q, nil, class: "form-control", height:"15", width:"15") %>
            </div>
          <% end %>
        </li>
        <li <%="class=active" if current_page?(itens_path) %>><%= link_to "Itens!", itens_path %></li>
        <li <%="class=active" if current_page?(generos_path) %>><%= link_to "Gêneros!", generos_path %></li>
        <li <%="class=active" if current_page?(categorias_path) %>><%= link_to "Categorias!", categorias_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Mais! <b class="caret"></b></a>
          <ul class="dropdown-menu">
          <li <%="class=active" if current_page?(sobre_path) %>><%= link_to "Sobre", sobre_path %></li>
          <li <%="class=active" if current_page?(privacidade_path) %>><%= link_to "Privacidade", privacidade_path %></li>
          <li <%="class=active" if current_page?(termos_path) %>><%= link_to "Termos", termos_path %></li>
          <li <%="class=active" if current_page?(contato_path) %>><%= link_to "Contato", contato_path %></li>
        </ul>
        </li>
      </ul>
      <!-- /Botões do navbar -->
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %> <!-- Está Logado -->
          <li><%= link_to "Suggest Me!", "/collaborative_recommendation" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src=<%= current_user.image %> alt="profile pic" height="25" width="25" class="img-rounded"> 
                <%= current_user.get_name.titleize %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to " Profile", current_user, class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to " Configuração", edit_usuario_path(current_user), class: "glyphicon glyphicon-globe" %></li>
              <li><%= link_to " Preferências", edit_preferences_path(current_user), class: "glyphicon glyphicon-edit" %></li>
              <li><%= link_to " Senha", { controller: :usuarios, action: :edit_password, id: current_user }, class: "glyphicon glyphicon-wrench" %></li>
                <li class="divider"></li>
                <li><%= link_to " Flags", flags_path, class: "glyphicon glyphicon-warning-sign" %></li>
              <li><%= link_to " Usuários", usuarios_path, class: "glyphicon glyphicon-signal" if admin? %></li>
              <li class="divider"></li>
              <li><%= link_to " Logout", signout_path, method: "delete", class: "glyphicon glyphicon-off" %></li>
            </ul>
          </li>
        <% else %>
          <form class="navbar-form navbar-right" role="form">
            <label>Olá estranho! </label>
            <%= link_to "Sign in com Facebook", "/auth/facebook", { class: "btn btn-social btn-facebook"} %>
            <%= link_to "Sign In", signin_path, { class: "btn btn-primary"} %>
            <%= link_to "Sign Up", signup_path, { class: "btn btn-primary"} %>
          </form>
        <% end %>
      </ul>
    </div><!--/.navbar-collapse -->
  </div><!--/.container -->
</div><!-- /Navigation Bar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suggest Me! Recomendações de Livros, Filmes, Jogos e Musicas</title>
    <%= include_gon %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application", media: "all" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="content">
    <div id="flash">
      <%= render 'compartilhado/flash', flash: flash %>
    </div>
    <!-- Content! -->
    <%= yield %>
    <!-- /Content! -->
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>